### ISSUE TITLE
Better known share icon on iOS

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#120]
The current share icon is an Android one. It would be better to have platform specific ones, like mentioned here https://github.com/FortAwesome/Font-Awesome/issues/14957 and discussed there https://github.com/FortAwesome/Font-Awesome/issues/10619

**Comment by SoleCincis** [comment]
Can We close this issue ? :)

**Comment by donni106** [comment]
sure, do it
