### ISSUE TITLE
[TypeScript] should we use recommended configs?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#126]
currently without recommended ruleset:

https://github.com/ikuseiGmbH/smart-village-app-app/blob/94bd1238af679bc33b72c53861317369ad81796d/.eslintrc.yml#L6-L8

should we add them?
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs

```
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
```

**Comment by digorath** [comment]
The `@typescript-eslint/recommended` ruleset will cause warnings regarding return types in `.js` files with our current setup, which is definitely not what we want. We could try to restrict those rules to `.ts` and `.tsx` files somehow?

The `@typescript-eslint/recommended-requiring-type-checking` does not immediately work with our current setup either. It causes the linting to fail immediately.
