### ISSUE TITLE
Sub-categories should be on a subpage of their parent category

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-app#179]
**Describe the bug**
All Categories are on the same level, even if they have a nested structure on the server. 

**Screenshots**
![Bildschirmfoto 2021-01-31 um 16 13 16](https://user-images.githubusercontent.com/664428/106388543-4156da80-63df-11eb-96c8-210c9a87f69e.png)

![106389204-6ac53580-63e2-11eb-9889-de948851614f](https://user-images.githubusercontent.com/1942953/152975384-2a3a841c-f9d0-4ecd-91b8-1edb5829606c.jpg)

**Comment by donni106** [comment]
Currently it is not possible to query the categories in a nested way.
We do:

```
query Categories {
  categories {
    id
    name
  }
}

```

and retrieve als the categories in a flat order:

```
{
  "data": {
    "categories": [
      {
        "id": "57",
        "name": "Aktiverlebnisse"
      },
      {
        "id": "82",
        "name": "Angebote für Kinder"
      },
      {
        "id": "26",
        "name": "Angelgewässer"
      },
      {
        "id": "28",
        "name": "Aussichtstürme"
      },
      {
        "id": "47",
        "name": "Ausstellung"
      },
      {
        "id": "90",
        "name": "Bauen, Wohnen und Sanieren"
      },
      {
        "id": "65",
        "name": "Besucherzentren"
      },
      {
        "id": "81",
        "name": "Bildung"
      },
      {
        "id": "25",
        "name": "Bühnen"
      },
      {
        "id": "4",
        "name": "Burgen"
      },
      {
        "id": "13",
        "name": "Campingplätze"
      },
      {
        "id": "58",
        "name": "category name"
      },
      {
        "id": "40",
        "name": "Chor / Folklore / Volksmusik"
      },
      {
        "id": "87",
        "name": "Digital"
      },
      {
        "id": "80",
        "name": "Engagement"
      },
      {
        "id": "75",
        "name": "Entspannung"
      },
      ...
```

Where do we have to take actions?
# GraphQL-Server returning hierarchical categories
# Mobile App rendering categories hierarchically in the list (parent-child-...), where every part navigates to entries for just their category (clicking on a parent does not have information about children on the next screen)

More ideas?

**Comment by donni106** [comment]
Meanwhile, there is the possibility to query for nested categories:

```
query Categories {
  categories {
    id
    name
    parent {
      id
      name
    }
    children {
      id
      name
    }
  }
}
```

and retrieve the categories like this:

```
{
  "data": {
    "categories": [
      {
        "id": "9",
        "name": "Reiterhöfe",
        "parent": null,
        "children": [
          {
            "id": "75",
            "name": "Spaß"
          }
        ]
      },
      {
        "id": "75",
        "name": "Spaß",
        "parent": {
          "id": "9",
          "name": "Reiterhöfe"
        },
        "children": [
          {
            "id": "76",
            "name": "Spaß 2"
          }
        ]
      },
      {
        "id": "76",
        "name": "Spaß 2",
        "parent": {
          "id": "75",
          "name": "Spaß"
        },
        "children": [
          {
            "id": "77",
            "name": "Spaß 4"
          }
        ]
      },
      {
        "id": "77",
        "name": "Spaß 4",
        "parent": {
          "id": "76",
          "name": "Spaß 2"
        },
        "children": []
      }
    ]
  }
}
```

this way we could achieve rendering a categories list with indented sub-categories as first step.

but the main aim is to provide a shorter list of categories. so we do not want to render all categories in one big list but render categories of one layer of categories and navigate to another list of categories of a sublayer. this way we reduce the rendered categories on screens.

**Comment by donni106** [comment]
done with #481
