### ISSUE TITLE
Liste für Navi

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-app#21]
- Übersicht
- Nachrichten
- Orte und Touren
- Veranstaltungen
- Bürger- und Unternehmensservice
- Fläming bewegt
- Maerker
- LAP (noch nicht einbinden)
- regiobus (noch nicht einbinden)
- Orte (noch nicht einbinden)
- Hintergrund
- Datenschutz
- Impressum

**Comment by pwilimzig** [comment]
Bitte die Navi erst einmal so umsetzen

**Comment by donni106** [comment]
![IMG_0F4F65271231-1](https://user-images.githubusercontent.com/1942953/59376154-de1ebd00-8d4f-11e9-9bd3-6ed925a79bb0.jpeg)
