### ISSUE TITLE
sectioned list for events

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#329]
for nicer overview it could help to have a sectioned list for events with the event date as section headline instead of a flat list with the event date just in the subtitle. it can be more difficult for users to check specific dates in the long list. sections would make it easier.

<img width="196" alt="Bildschirmfoto 2021-09-15 um 15 56 02" src="https://user-images.githubusercontent.com/1942953/133450622-8c17b256-eb6e-4270-85cc-9d77f47fb48f.png">

**Comment by digorath** [comment]
closed by #375
