### ISSUE TITLE
Text Changes

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-app#35]
Please include the Texts in die Document [201907_BelzigApp_Texte.docx](https://github.com/ikuseiGmbH/smart-village-app-app/files/3411578/201907_BelzigApp_Texte.docx) into the app.

Maybe you will also need some Logos, they can be found here: https://smart-village.app/

**Comment by donni106** [comment]
This needs to be done in the main-server at public contents and should not be public on GitHub, but in the branch release/bad-belzig-app in our Bitbucket @SoleCincis @pwilimzig.
