### ISSUE TITLE
Add information text to empty screens

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#49]
Currently screens are empty and white, if there is no data.
I would be nice to have a short text on screens without data. An empty screen is always bad user experience.

|example from GitHub app|example Google Play|example Expo|
|---|---|---|
|![Screenshot_20200513-104755](https://user-images.githubusercontent.com/1942953/81791817-8496b380-9507-11ea-8b42-ea52098022e8.png)|![Screenshot_20220119-181156](https://user-images.githubusercontent.com/1942953/150180617-ea1e1f44-bcfe-4708-a2ce-494abc8c3207.png)|![Screenshot_20220119-204559](https://user-images.githubusercontent.com/1942953/150202982-78846b5a-65b6-4f56-ab91-db43434429fe.png)|

**Comment by SoleCincis** [comment]
I would be happy to work on this feature if requested

**Comment by donni106** [comment]
there are a few examples where this could happen. two of them are pointed out in the following table with screenshots.

|home screen events widget|no events|home screen about item|no content|
|---|---|---|---|
|![Simulator Screen Shot - iPhone 8 Plus - 2022-01-19 at 18 01 31](https://user-images.githubusercontent.com/1942953/150178917-29fbf1f5-2b35-4504-9eb3-0d772d9a21b7.png)|![Simulator Screen Shot - iPhone 8 Plus - 2022-01-19 at 18 01 35](https://user-images.githubusercontent.com/1942953/150178931-bf50527e-521e-428d-85aa-fbaaa2fdfd97.png)|![Simulator Screen Shot - iPhone 8 Plus - 2022-01-19 at 18 01 49](https://user-images.githubusercontent.com/1942953/150178965-cf0f9af1-a58d-4f2c-adb4-a54762fb4e67.png)|![Simulator Screen Shot - iPhone 8 Plus - 2022-01-19 at 18 01 51](https://user-images.githubusercontent.com/1942953/150178973-df22e4d6-a1fb-4cff-b9d9-1f2212fd0354.png)|

it would be nice to have some default message saying that there is nothing to see. maybe some sort of fallback component for empty things.
