### ISSUE TITLE
Rename link prop on text component 

### ISSUE THREAD

**Issue by SoleCincis** [ikuseiGmbH/smart-village-app-app#50]
In text style component, 'link' prop of regular text  needs to be renamed primary : this prop dyes regular text  in primary colour across the app .

**Comment by SoleCincis** [comment]
I would be happy to work on this feature if requested

**Comment by donni106** [comment]
https://github.com/ikuseiGmbH/smart-village-app-app/blob/9f1d333591c472a14bfdda65948c556b3df60966/src/components/Text.js#L17-L21

**Comment by SoleCincis** [comment]
all right can we close this then ?

**Comment by donni106** [comment]
?? nothing happened yet. I just posted the code lines, which need to be addressed.

**Comment by SoleCincis** [comment]
PR on going https://github.com/ikuseiGmbH/smart-village-app-app/pull/79
