### ISSUE TITLE
Missing information about licensing

### ISSUE THREAD

**Issue by github-luckow-org** [ikuseiGmbH/smart-village-app-app#505]
Just a quick question: Under which licence do you offer your "open source React Native app"? I can't find anything about it in the repo.

**Comment by pwilimzig** [comment]
Hi @github-luckow-org Very sorry for the late answer and the missing licence. We will fix that. Until then: https://github.com/Bad-Belzig/smart-village-app-app/blob/master/LICENSE - as you can see here, it is the GPLv3.
