### ISSUE TITLE
Consul: store only consul user id instead of whole user object

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-app#574]
In the consul helper we store a json object with user data.

https://github.com/ikuseiGmbH/smart-village-app-app/blob/44804b6416b398e875fc346eab5321f9a1b23fcd/src/helpers/consul/index.js#L16-L24

I think we can store just the user id, as we never do something different then the following in five different files:

```js
getConsulUser().then((userInfo) => {
  if (userInfo) return setUserId(JSON.parse(userInfo).id);
});
```

We avoid storing a complex json object with parsing this way in favor of a simpler string.
Please also think about a way to reduce duplication of getting the user id in that five files.

**Comment by ardasnturk** [comment]
I solved this problem in pr https://github.com/ikuseiGmbH/smart-village-app-app/pull/589
